### ISSUE TITLE
[Feature request] multiple servers

### ISSUE THREAD

**Issue by ergoz** [rainloreley/shlink-manager#3]
I use shlink for multiple domains with multiple installations, it will be great if i could add more than one server and have ability to fast switch between them without logging out.

**Comment by rainloreley** [comment]
Hey @ergoz, great idea!
I just published an update with this feature. You can now click on the URL beneath the title in the main view or on the server details within the settings view to toggle between different Shlink instances and to add more or remove them. I hope this helps!
